# Generated by Django 3.2 on 2022-08-14 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_movie_price_4k'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
