# Generated by Django 3.2 on 2022-08-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_movie_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_on']},
        ),
    ]
