# Generated by Django 3.2 on 2022-08-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
    ]
