# Generated by Django 3.2 on 2022-08-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_movie_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='price_dvd',
            new_name='price',
        ),
    ]
