# Generated by Django 3.2 on 2022-08-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_price_dvd_movie_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_on']},
        ),
    ]
